<?php include 'modals/client_list_model.php';?>
<?php include 'modals/new_order_modal.php';?>
<?php include 'modals/create_client_modal.php';?>
<?php include 'modals/new_jobCard_modal.php';?>
<?php include 'modals/add_order_modal.php';?>
<?php include 'modals/workLog_modal.php';?>
<?php include 'modals/edit_purchase_modal.php';?>
<?php include 'modals/edit_product_modal.php';?>
<?php include 'modals/edit_type_modal.php';?>
<?php include 'modals/edit_size_modal.php';?>
<?php include 'modals/edit_units_modal.php';?>
<?php include 'modals/edit_orderStatus_modal.php';?>
<?php include 'modals/edit_machine_modal.php';?>
<?php include 'modals/preorder_modal.php';?>
<?php include 'modals/edit_matcat_modal.php';?>
<?php include 'modals/edit_mat_modal.php';?>
<?php include 'modals/edit_suplly_modal.php';?>
<?php include 'modals/edit_employees_modal.php';?>
<?php include 'modals/set_order_modal.php';?>
<?php include 'modals/create_size_modal.php';?>